CS296N_Term_Project/Controllers/ImageController.cs
using CS296N_Term_Project.Models;
using CS296N_Term_Project.Models.DataLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Web;
using System.Linq;
using System.Threading.Tasks;
using CS296N_Term_Project.Models.ViewModels;

namespace CS296N_Term_Project.Controllers
{
    public class ImageController : Controller
    {
        private IPostRepo repo;

        private UserManager<AppUser> userManager;

        public ImageController(IPostRepo ctx, UserManager<AppUser> u)
        {
            repo = ctx;
            this.userManager = u;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ViewBag.ImagePosts = await repo.SelectImagesAsync();
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> SingleImage(int id)
        {
            ViewBag.ImagePost = await repo.SelectImagesByIdAsync(id);
            CommentVM temp = new CommentVM();
            //temp.PostId = id;
            return View(temp);
        }

        [HttpPost]
        [Authorize]
        //TODO: Fix adding comments and loading them
        public async Task<IActionResult> SingleImage(CommentVM comment)
        {
            var user = userManager.GetUserAsync(User).Result;
            ImageComment temp = new ImageComment();
            temp.Description = comment.Description;
            //temp.Post = await repo.SelectImagesByIdAsync(comment.PostId);
            temp.Commenter = user;

            var post = (from p in repo.Images
                        where p.PostId == comment.PostId
                        select p).First<ImagePost>();
            post.AddComment(temp);
            //repo.Insert(temp);
            await repo.SaveAsync();
            return RedirectToAction("SingleImage", comment.PostId);
            //return View("SingleImage", comment.imagePost.PostId);
        }

        [HttpGet]
        public async Task<IActionResult> ImageUpload()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ImageUpload(ImagePost newPost)
        {
            var user = userManager.GetUserAsync(User).Result;
            newPost.UserId = user.Id;
            newPost.PosterName = user.ScreenName;
            newPost.Likes = 0;
            //repo.Insert(newPost);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Search()
        {
            string search = "";
            ViewBag.ImagePosts = await repo.SearchImagesAsync(search);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Search(string search = "")
        {
            ViewBag.ImagePosts = await repo.SearchImagesAsync(search);
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        //=============================================================================================================================

        private readonly long _fileSizeLimit = 2097162; // 2,097,162
        private readonly string[] _permittedExtensions = { ".png", ".jpg", ".jpeg", ".gif" };
        private readonly string _targetFilePath = Path.GetFullPath(@"wwwroot\MagicaVoxelImages");
        //HttpContext.Current.Server.MapPath(@"~\wwwroot\MagicaVoxelImages");
        public string Result { get; private set; }
        [Authorize]
        [HttpGet]
        public IActionResult Upload()
        {
            NewPostVM model = new NewPostVM();
            return View(model);
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Upload(NewPostVM newPost)
        {

            if (!ModelState.IsValid)
            {
                Result = "Please correct the form.";

                return View();
            }

            var formFileContent =
                await FileHelpers.ProcessFormFile<BufferedSingleFileUploadPhysical>(
                    newPost.Image.FormFile, ModelState, _permittedExtensions,
                    _fileSizeLimit);

            if (!ModelState.IsValid)
            {
                Result = "Please correct the form.";
                return View();
            }

            // For the file name of the uploaded file stored
            // server-side, use Path.GetRandomFileName to generate a safe
            // random file name.
            var trustedFileNameForFileStorage = Path.GetRandomFileName();
            var filePath = Path.Combine(
                _targetFilePath, trustedFileNameForFileStorage);

            // **WARNING!**
            // In the following example, the file is saved without
            // scanning the file's contents. In most production
            // scenarios, an anti-virus/anti-malware scanner API
            // is used on the file before making the file available
            // for download or for use by other systems. 
            // For more information, see the topic that accompanies 
            // this sample.

            using (var fileStream = System.IO.File.Create(filePath))
            {
                await fileStream.WriteAsync(formFileContent);
                string[] splitPath = fileStream.Name.Split("\\");
                newPost.imagePost.Path = "/MagicaVoxelImages/" + splitPath[splitPath.Length-1];
                // To work directly with a FormFile, use the following
                // instead:
                //await FileUpload.FormFile.CopyToAsync(fileStream);
            }

            //Add stuff to DB --fileStream
            var user = userManager.GetUserAsync(User).Result;
            newPost.imagePost.UserId = user.Id;
            newPost.imagePost.PosterName = user.ScreenName;
            newPost.imagePost.Likes = 0;
            repo.Insert(newPost.imagePost);
            await repo.SaveAsync();

            return RedirectToAction("Index");
        }
    }
}

CS296N_Term_Project/Controllers/VideoController.cs
using CS296N_Term_Project.Models;
using CS296N_Term_Project.Models.DataLayer;
using CS296N_Term_Project.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CS296N_Term_Project.Controllers
{
    public class VideoController : Controller
    {
        private IPostRepo repo;

        private UserManager<AppUser> userManager;

        public VideoController(IPostRepo ctx, UserManager<AppUser> u)
        {
            repo = ctx;
            this.userManager = u;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ViewBag.VideoPosts = await repo.SelectVideosAsync();
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> SingleVideo(int id)
        {
            ViewBag.VideoPost = await repo.SelectVideoByIdAsync(id);
            CommentVM temp = new CommentVM();
            return View(temp);
        }

        [HttpPost]
        [Authorize]
        //TODO: Fix adding comments and loading them
        public async Task<IActionResult> SingleVideo(CommentVM comment)
        {
            var user = userManager.GetUserAsync(User).Result;
            VideoComment temp = new VideoComment();
            temp.Description = comment.Description;
            //temp.Post = await repo.SelectImagesByIdAsync(comment.PostId);
            temp.Commenter = user;

            var post = (from p in repo.Videos
                        where p.PostId == comment.PostId
                        select p).First<VideoPost>();
            post.AddComment(temp);
            //repo.Insert(temp);
            await repo.SaveAsync();
            return RedirectToAction("SingleVideo", comment.PostId);
            //return View("SingleImage", comment.imagePost.PostId);
        }

        [HttpGet]
        public async Task<IActionResult> Search()
        {
            string search = "";
            ViewBag.VideoPosts = await repo.SearchVideosAsync(search);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Search(string search = "")
        {
            ViewBag.VideoPosts = await repo.SearchVideosAsync(search);
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        //=============================================================================================================================

        private readonly long _fileSizeLimit = 2097162; // 2,097,162
        private readonly string[] _permittedExtensions = { ".mp4", ".mov", ".avi", ".wmv" };
        private readonly string _targetFilePath = Path.GetFullPath(@"wwwroot\MagicaVoxelVideos");
        //HttpContext.Current.Server.MapPath(@"~\wwwroot\MagicaVoxelImages");
        public string Result { get; private set; }
        [Authorize]
        [HttpGet]
        public IActionResult Upload()
        {
            NewPostVM model = new NewPostVM();
            return View(model);
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Upload(NewPostVM newPost)
        {

            if (!ModelState.IsValid)
            {
                Result = "Please correct the form.";

                return View();
            }

            var formFileContent =
                await FileHelpers.ProcessFormFile<BufferedSingleFileUploadPhysical>(
                    newPost.Image.FormFile, ModelState, _permittedExtensions,
                    _fileSizeLimit);

            if (!ModelState.IsValid)
            {
                Result = "Please correct the form.";
                return View();
            }

            // For the file name of the uploaded file stored
            // server-side, use Path.GetRandomFileName to generate a safe
            // random file name.
            var trustedFileNameForFileStorage = Path.GetRandomFileName();
            var filePath = Path.Combine(
                _targetFilePath, trustedFileNameForFileStorage);

            // **WARNING!**
            // In the following example, the file is saved without
            // scanning the file's contents. In most production
            // scenarios, an anti-virus/anti-malware scanner API
            // is used on the file before making the file available
            // for download or for use by other systems. 
            // For more information, see the topic that accompanies 
            // this sample.

            using (var fileStream = System.IO.File.Create(filePath))
            {
                await fileStream.WriteAsync(formFileContent);
                string[] splitPath = fileStream.Name.Split("\\");
                newPost.videoPost.Path = "/MagicaVoxelImages/" + splitPath[splitPath.Length - 1];
                // To work directly with a FormFile, use the following
                // instead:
                //await FileUpload.FormFile.CopyToAsync(fileStream);
            }

            //Add stuff to DB --fileStream
            var user = userManager.GetUserAsync(User).Result;
            newPost.videoPost.UserId = user.Id;
            newPost.videoPost.PosterName = user.ScreenName;
            newPost.videoPost.Likes = 0;
            repo.Insert(newPost.videoPost);
            await repo.SaveAsync();

            return RedirectToAction("Index");
        }
    }
}

CS296N_Term_Project/Views/Video/Index.cshtml
@{
    ViewData["Title"] = "VideoPosts";
}


<main>
    <a class="nav-link text-dark" asp-area="" asp-controller="Video" asp-action="Upload">Upload</a>
    <a class="nav-link text-dark" asp-area="" asp-controller="Video" asp-action="Search">Search</a>
    <div class="flex-parent">
        @foreach (VideoPost post in ViewBag.VideoPosts)
        {
            <a class="nav-link text-dark" asp-area="" asp-route-id="@post.PostId" asp-controller="Video" asp-action="SingleVideo">
                <div class="post-obj">
                    <h3 class="post-obj-title">@post.Title</h3>
                    <img src=@post.ThumbPath alt="Post Thumbnail" class="post-obj-img">
                    <div class="post-obj-top">
                        <h5 class="poster-name">@post.PosterName </h5>
                        <img src="https://icones.pro/wp-content/uploads/2021/04/icone-noire-noir.png" alt="Like Button" class="post-like-button">
                    </div>
                    <div class="post-obj-bottom">
                        <h6 class="post-description">@post.Description</h6>
                    </div>
                </div>
            </a>
        }
    </div>
</main>

CS296N_Term_Project/Views/Video/Search.cshtml
@{
    ViewData["Title"] = "Search";
}


<main>
    <div class="flex-parent">

        <form asp-action="Search" asp-controller="Video" method="POST">
            <input type="text" name="search" id="search" />
            <button type="submit" id="SearchBar">Search</button>
        </form>

        @foreach (VideoPost post in ViewBag.VideoPosts)
        {
            <a class="nav-link text-dark" asp-area="" asp-route-id="@post.PostId" asp-controller="Image" asp-action="SingleImage">
                <div class="post-obj">
                    <h3 class="post-obj-title">@post.Title</h3>
                    <img src=@Url.Content(post.ThumbPath) alt="Post Image" class="post-obj-img">
                    <div class="post-obj-top">
                        <h5 class="poster-name">@post.PosterName </h5>
                        <img src="https://icones.pro/wp-content/uploads/2021/04/icone-noire-noir.png" alt="Like Button" class="post-like-button">
                    </div>
                    <div class="post-obj-bottom">
                        <h6 class="post-description">@post.Description</h6>
                    </div>
                </div>
            </a>
        }
    </div>
</main>

CS296N_Term_Project/Views/Video/SingleVideo.cshtml
@model CommentVM;
@{
    ViewData["Title"] = "SingleVideo";
}


<main>
    <h1 class="post-obj-title">@ViewBag.VideoPost.Title</h1>
    <img src="@Url.Content(ViewBag.VideoPost.Path)" alt="Post Video" class="post-obj-img">
    <div class="single-post-obj-top">
        <h5 class="poster-name">@ViewBag.VideoPost.PosterName</h5>
        <img src="https://icones.pro/wp-content/uploads/2021/04/icone-noire-noir.png" alt="Like Button" class="post-like-button">
    </div>
    <div class="post-obj-bottom">
        <h6 class="post-description">@ViewBag.VideoPost.Description</h6>
    </div>
    <div class="post-comments">
        <h3>Comments</h3>
        <form asp-action="SingleVideo" class="post-add-comment">
            <textarea placeholder="Comment" asp-for="Description"></textarea>
            <input type="hidden" asp-for="PostId" value="@ViewBag.VideoPost.PostId" />
            <button type="submit" class="btn btn-primary">Comment</button>
        </form>
        @if (ViewBag.VideoPost.GetComments() != null)
        {
            @foreach (ImageComment comment in ViewBag.VideoPost.GetComments())
            {
                <div class="post-comment">
                    <h3 class="commenter-name">@comment.Commenter.ScreenName</h3>
                    <p class="comment-content">@comment.Description</p>
                </div>
            }
        }
    </div>
</main>

CS296N_Term_Project/Views/Video/Upload.cshtml
@model CS296N_Term_Project.Models.ViewModels.NewPostVM

@{
    ViewData["Title"] = "Upload";
}
<form enctype="multipart/form-data" method="post">
    <dl>
        <input class="upload-title" type="text" asp-for="@Model.videoPost.Title" />
        <textarea class="upload-description" placeholder="Description" asp-for="@Model.videoPost.Description"></textarea>
        <dt>
            <label asp-for="@Model.Image.FormFile"></label>
        </dt>
        <dd>
            <input asp-for="@Model.Image.FormFile" type="file" />
            <span asp-validation-for="@Model.Image.FormFile"></span>
        </dd>
    </dl>
    <input asp-page-handler="Upload" class="btn btn-primary" type="submit" value="Upload" />
</form>